# Generated by Django 5.0.2 on 2024-03-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
