# Generated by Django 5.0.2 on 2024-03-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurahExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('explanation', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='basic_endpoints.surah')),
            ],
        ),
        migrations.CreateModel(
            name='SurahText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('text', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='basic_endpoints.surah')),
            ],
        ),
    ]
