# Generated by Django 5.0.2 on 2024-03-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0002_surahexplanation_surahtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surahexplanation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='surahexplanation',
            name='verse_number',
        ),
        migrations.RemoveField(
            model_name='surahtext',
            name='id',
        ),
        migrations.RemoveField(
            model_name='surahtext',
            name='verse_number',
        ),
        migrations.AddField(
            model_name='surahexplanation',
            name='expl_number',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surahtext',
            name='ayah_number',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
