# Generated by Django 5.0.2 on 2024-03-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0003_remove_surahexplanation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surahtext',
            old_name='text',
            new_name='ayah_text',
        ),
        migrations.RemoveField(
            model_name='surahtext',
            name='surah',
        ),
        migrations.AddField(
            model_name='surahtext',
            name='surah_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surahtext',
            name='text_number',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surahexplanation',
            name='surah',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='surahtext',
            name='ayah_number',
            field=models.IntegerField(),
        ),
    ]
