# Generated by Django 5.0.2 on 2024-03-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0005_alter_surahexplanation_surah_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surahexplanation',
            old_name='surah',
            new_name='surah_name',
        ),
    ]
