# Generated by Django 5.0.2 on 2024-03-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0007_rename_expl_number_surahexplanation_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surahexplanation',
            unique_together={('surah_name', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='surahtext',
            unique_together={('surah_name', 'id')},
        ),
    ]
