# Generated by Django 5.0.2 on 2024-03-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0008_alter_surahexplanation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surahexplanation',
            old_name='id',
            new_name='expl_number',
        ),
        migrations.RenameField(
            model_name='surahtext',
            old_name='id',
            new_name='text_number',
        ),
        migrations.AlterUniqueTogether(
            name='surahexplanation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='surahtext',
            unique_together=set(),
        ),
    ]
