# Generated by Django 5.0.2 on 2024-03-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0010_surahexplanation_id_surahtext_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surahexplanation',
            name='controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surahtext',
            name='controlled',
            field=models.BooleanField(default=False),
        ),
    ]
