# Generated by Django 5.0.2 on 2024-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0012_surahtexttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='surahtexttext',
            name='value',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
