# Generated by Django 5.0.2 on 2024-03-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_endpoints', '0013_surahtexttext_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurahTextText',
        ),
    ]
